### ISSUE TITLE
getLocale on entry.server.ts not work

### ISSUE THREAD

**Issue by eliawk** [sergiodxa/remix-i18next#127]
### Describe the bug

On `entry.server.ts` this
`let lng = await i18next.getLocale(request)` return always the same language

### Your Example Website or App

https://github.com/piramid-dev/buyers-test-hydro/tree/feature/routes-localization-i18n

### Steps to Reproduce the Bug or Issue

1. Open /it/prodotti
2. getLocale return language **IT** (correct), and I get `<html lang="IT" dir="ltr">`
3. Open /en/products
4. getLocale return language **IT** (**not correct!**) but I get `<html lang="EN" dir="ltr">`

But in both case the html tag is correctly setup

### Expected behavior

I would expect to have **getLocale** reflecting the language of the page I currently loading

### Platform

- OS: macOS
- Browser: Chrome

### Additional context

The project I'm working on is the basic demo of Hydrogen, which is a little bit different form the basic Remix starer

**Comment by mjsol12** [comment]
I have experienced the same error, and it returns a `Warning: Text content did not match. Server: "Login" Client: "Iniciar sesión"` and upon investigation I've landed in `getLocale(request)` which always returns the fallback language currently 'en' during the first load and messes up the page.

**Comment by juniorforlife** [comment]
@mjsol12 how did you solve the problem?

**Comment by mjsol12** [comment]
@juniorforlife , In my case I was using the cookie and it need to provide the cookie on the this part.
```
 export const langSessionCookie = createCookie('i18n', {
  path: '/',
  sameSite: 'lax',
});
```
 ```
return new RemixI18Next({
    detection: {
      cookie: langSessionCookie, // you also need this to read the locale
      supportedLanguages: i18n.supportedLngs,
      fallbackLanguage: i18n.fallbackLng,
    },
  });
```

**Comment by juniorforlife** [comment]
@mjsol12 thanks mate!

**Comment by peterbrczan** [comment]
@mjsol12 could you provide a sample repo/snippets with your configs because for me it still doesn't want to work. First it loads the page in `en` then switches to my selected one. Strange, that it works well locally 🤔

**Comment by peterbrczan** [comment]
I think my issue, is not related to this package, or to the config, but to the hosting platform. I'm using Vercel, and looks like it's challenging to access/load the resources from it's built output. I've even hardcoded the `https://...../locales/en/common.json` as a `loadPath` but still did not load and rendered it.

**Comment by sergiodxa** [comment]
> I think my issue, is not related to this package, or to the config, but to the hosting platform. I'm using Vercel, and looks like it's challenging to access/load the resources from it's built output. I've even hardcoded the `https://...../locales/en/common.json` as a `loadPath` but still did not load and rendered it.

There has been few issues open in the past about using Vercel and the i18next-fs-backend, it basically doesn't work on Vercel, it's better to put everything in memory server-side or to use the fetch backend and fetch it from the deployment.

**Comment by Baterka** [comment]
Yeah... This is very confusing. This library should follow same detection rules as `https://github.com/i18next/i18next-browser-languageDetector`:
```
cookie (set cookie i18next=LANGUAGE)
sessionStorage (set key i18nextLng=LANGUAGE)
localStorage (set key i18nextLng=LANGUAGE)
navigator (set browser language)
querystring (append ?lng=LANGUAGE to URL)
htmlTag (add html language tag <html lang="LANGUAGE" ...)
path (http://my.site.com/LANGUAGE/...)
subdomain (http://language.site.com/...)
```

I was stuck like 2 hours on similar issue, because I am not using any of the supported Remix-i18next detection methods `searchParams, cookie, session, header` but I am using `path (http://my.site.com/LANGUAGE/...)` method.

**Comment by sergiodxa** [comment]
@Baterka those detection rules won't work because most of those things are client-side only.

Cookie support, (Remix) sessionStorage support, query string and the Accept-Language headers are all supported and in that order.

Path and subdomains are easier to build yourself in Remix, e.g. using optional route params and then `params.lang ?? fallbackLanguage` in your loader or extracting from the subdomain with request.url.

Anyway, any PR to improve it is welcomed, but remember that this library runs server-side, not client-side so i18next-**browser**-languageDetector heuristics will not apply
