### ISSUE TITLE
Is it possible to get the direction of the language in loader? (LTR/RTL)

### ISSUE THREAD

**Issue by mehrad77** [sergiodxa/remix-i18next#46]
I want to be able to set it in elements `direction` prop to properly show the page in those languages.

**Comment by sergiodxa** [comment]
The library only gives you the locale, it's focused on that because it's needed to identify what translations to load to how on the UI.

If you know based on the locale the direction of the text you could do a function like

```ts
function getDirection(locale: string): "ltr" | "rtl" {
  if (locale === "es") return "ltr"
  if (locale === "jp") return "rtl" // I think jp uses rtl
  // add more or build a JSON with { [locale]: direction }
}
```

Then you can call that in the root loader and return the direction.

---

That said, I think it's a simple feature to add and the direction is not something that's going to change anyway, so maybe I could add it, do you happen to know if there's some public JSON with all the locales and their direction? That way I could bundle it on the server-side part and give you a method to get the direction directly on `i18n.getDirection`

**Comment by mehrad77** [comment]
There is [this `.dir()` method](https://www.i18next.com/overview/api#dir) in `i18next` and since `remix-i18next` is based on that, I though there must be a way of using that built-in method.  [(This is the array which they use in order to detect RTL languages)](https://github.com/i18next/i18next/blob/3a2db93b04104556f959e10b4f8f356925685c85/src/i18next.js#L495)

**Comment by mehrad77** [comment]
@sergiodxa I'm very eager to have contributions to this project. If you are ok with it, until the end weekend I'll get back with an MR for this issue

**Comment by sergiodxa** [comment]
> There is [this `.dir()` method](https://www.i18next.com/overview/api#dir) in `i18next` and since `remix-i18next` is based on that, I though there must be a way of using that built-in method. [(This is the array which they use in order to detect RTL languages)](https://github.com/i18next/i18next/blob/3a2db93b04104556f959e10b4f8f356925685c85/src/i18next.js#L495)
> 
> Although we in our project only use `ISO 639-2` languages codes (which are 3 character length) so we properly need to write a utility function for that but for other cases using built-in `.dir()` method would be acceptable for general user.

I just saw that dir method, and you can use it right now like this:
```ts
let { i18n } = useTranslation() // this hook comes from react-i18next
i18n.dir() // this is the dir method you mentioned
```

Is there an scenario where you may need that inside loaders/actions?
